export default function BackAlleyPinkGlow() {
  return (
    <>
      <pointLight
        name="backAlleyUpperPinkFill"
        position={[
          1.8,
          5.2,
          -1.8,
        ]}
        intensity={
          22
        }
        distance={
          12
        }
        decay={
          1.5
        }
        color="#ff6eb4"
      />

      <pointLight
        name="backAlleyMiddlePinkFill"
        position={[
          2.4,
          3.2,
          -2.6,
        ]}
        intensity={
          18
        }
        distance={
          11
        }
        decay={
          1.55
        }
        color="#ff82b8"
      />

      <pointLight
        name="backAlleyLowerPinkFill"
        position={[
          2,
          0.6,
          -2.2,
        ]}
        intensity={
          14
        }
        distance={
          10
        }
        decay={
          1.6
        }
        color="#ff90c0"
      />

      <pointLight
        name="backAlleyHighPinkFill"
        position={[
          1.6,
          7.8,
          -1.4,
        ]}
        intensity={
          12
        }
        distance={
          10
        }
        decay={
          1.65
        }
        color="#ff78be"
      />
    </>
  );
}
